sudo: false
os:
  - osx

install:
  - npm install
  - npm run vscode:prepublish

jobs:
  include:
    - stage: Version Check
      if: branch = feature/auto-update
      script:
        - LATEST_VERSION=$(curl --silent "https://api.github.com/repos/pmd/pmd/releases/latest" | grep -Po '"tag_name":\ "\K.*?(?=")')
        - LATEST_VERSION=${LATEST_VERSION:13:10}
        - CURRENT_VERSION=$(git describe)
        - echo $LATEST_VERSION
        - echo $CURRENT_VERSION
        - |
          if [[ "$LATEST_VERSION" != "$CURRENT_VERSION" ]]; then
            npm run update-pmd
            git add .
            git commit -m 'Update to v$LATEST_VERSION'
            git push
          fi
